/*
####  Coloured Triangles  ####

A coloured triangle is created from different rows of colours (Red, Green or Blue). Successive rows, each containing one fewer colour than the last, are generated by considering the two touching colours in the previous row. If these colours are identical, the same colour is used in the new row. If colours are different, the missing colour is used in the new row. This process continues untill a single colour is generated in the final row.
Different possibilities of colours are:
___
Colours Touching:        G G        B G        R G        B R
New colour:               G          R          B          G
_____

With a bigger example:
___
R R G B R G B B
 R B R G B R B
  G G B R G G
   G R G B G
    B B R R
     B G R
      R B
       G
_____



[Goal]

___
*) Create a function which takes first row of the triangle as an input and returns the final colour which would appear at the bottom row. In above example, given input "RRGBRGBB" will return "G".
*) If you are only given one colour as the input, return that colour.
*) There will be no exception handling case.
___



[Examples]

___
colouredTriangle("B") ➞ "B"

colouredTriangle("GB") ➞ "R"

colouredTriangle("RBRGBRB") ➞ "G"
_____



[Notes]

N/A


[games] [language_fundamentals] [strings] 



-------------------------------------------------------------------
[Resources]
_________
Array.prototype.filter()
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter
Creates a new array with all elements that pass the test implemented by the provided function.
_________
_________
Conditional Operator
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator
Is the only JavaScript operator that takes three operands: a condition followed by a question mark (?), then an expression to execute if the condition is truthy followe …
_________
_________
Learn Data Structure and Algorithm in JavaScript | Part 08 - DEV
https://dev.to/edisonnpebojot/learn-data-structure-and-algorithm-in-javascript-part-08-5456
💡Viktor V. 💻 @the_vikvel... Tagged with javascript, computerscience, datastructures, algorithms.
_________

*/
//Your code should go here:

